theme: jekyll-theme-minimal
title: Willoughby Seago
description: PhD student in mathematics and Maclaurin scholar at the University of Glasgow

include:
- _pages

minima:
  nav_pages:
    - 01_about.md
