theme: minima
title: Willoughby Seago
description: PhD student in mathematics and Maclaurin scholar at the University of Glasgow

include:
- _pages

minima:
  nav_pages:
    - about.md
    - teaching.md
    - talks.md
    - conferences.md
    - contact.md

header_pages:
  - _pages/about.md
  - _pages/teaching.md
  - _pages/talks.md
  - _pages/conferences.md
  - _pages/contact.md
